version: "3.7"
services:

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    network_mode: "bridge"
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker-portainer/portainer_data:/data
      - /public:/public